'ECOSYSTEM 

'Earth system
'****Initial values
'eq 10.01
series SES
SES=K_c+K_p+K_k 'Initial value of socio-economic stock
SES.label(d) Socio-economic stock 
'eq 10.02
series SES_dis
SES_dis=0
SES_dis.label(d) Discarded socio-economic stock
series dc
dc = C_total  'Stock of durable goods in the first period
dc.label(d) Stock of durable consumption goods 
'Conflit SES avec 10.05 variables dc ou SES
'eq 10.03
series MAT_y
MAT_y.label(d) Production of material goods
'eq 10.05
series MAT_ext
MAT_ext=0
MAT_ext.label(d) Extraction of matter
'eq 10.06
series SES_rec
SES_rec=0
SES_rec.label(d) Recycled socio-economic stock 
'eq 10.07
series SES_wa
SES_wa=0
SES_wa.label(d) Waste generated by production activities
'eq 10.08
series MAT_rev
MAT_rev = 6438 'Initial value for matter reserves  
MAT_rev.label(d) Stock of material reserves
'eq 10.09
series MAT_con
MAT_con=0
MAT_con.label(d) Material resources converted to reserves
'eq 10.10 
series MAT_res
MAT_res=834490000
MAT_res.label(d) Stock of material resources

'****Variable Parameters
'eq 10.04
series mu_mat
mu_mat.label(d) Matter intensity coefficient
series mu_g
mu_g = 0.71 ''Material intensity of green capital (Kg/USD) 
mu_g.label(d) Matter intensity coefficient of green production 
series mu_b
mu_b = 0.86 'Material intensity of conventional capital (Kg/USD)
mu_b.label(d) Matter intensity coefficient of conventional production 

'****Fixed Parameters
'eq 10.02
series zeta
zeta = 0.015 'Proportion of durable discarded
zeta.label(d) Proportion of durable goods discarded every year
'eq 10.06
series rho_rec 
rho_rec = 0.05 'Recycling rate  
rho_rec.label(d) Percentage of recycling
'eq 10.09
series sigma_mat
sigma_mat = 0.001 'Conversion rate of material resources into reserves
sigma_mat.label(d) Percentage of material resources converted to reserves 


'Energy system
'****Initial values
'eq 10.20
series EN_rev
EN_rev = 38000 'Initial value of non renewable energy reserves (Ej)
EN_rev.label(d) 'Stock of energy reserves
'eq 10.21
series EN_con
EN_con=0
EN_con.label(d) 'Energy resources converted to reserves
series EN_res
EN_res= 543000000000
EN_res.label(d) ‘Stock of energy resources
'eq 10.22
series EN_nre
EN_nre=93200
EN_nre.label(d) 'Non-renewable energy
'eq 10.23
series EN_re
EN_re=0
EN_re.label(d) Renewable energy
'eq 10.24
series EN
EN=93200
EN.label(d) Energy required for production
'eq 10.26
series EN_dis
EN_dis=0
EN_dis.label(d) 'Dissipated energy at the end of the period  

'****Fixed Parameters
'eq 10.21
series sigma_en
sigma_en = 0.0177
sigma_en.label(d) Percentage of energy resources converted to reserves 
'eq 10.24
series xi_Y
xi_Y = 1 / (0.0000035)
'eq 10.25
series kappa_tek
kappa_tek = 150


'Emissions
'****Initial values
'eq 10.30
series CO2_ob
CO2_ob= 36.17
CO2_ob.label(d) 2017 world-wide industrial emissions of CO2
series CO2_em
CO2_em = CO2_ob
CO2_em.label(d) World-wide industrial emissions of CO2
'eq 10.31
series CO2_lnd
CO2_lnd = 4 
CO2_lnd.label(d) Annual land emissions of CO2
'eq 10.32
series CO2_ind
CO2_ind = (CO2_ob-CO2_lnd)
CO2_ind.label(d) Industrial emissions of CO2 
'eq 10.33
series O2
O2=0
O2.label(d) Mass of oxygen
'eq 10.34
series CO2_mas
CO2_mas=0
CO2_mas.label(d) Carbon mass of (non-renewable) energy

'****Variable Parameters
'eq 10.32
series beta0 
beta0.label(d) Initial value of CO2 emissions

'****Fixed Parameters
'eq 10.32
series g_lnd
g_lnd.label(d) Rate of decline of land-use CO2 emissions*
'eq 10.34
series car 
car = 0.0305 'Coefficient converting Gt of carbon into Gt of CO2
car.label(d) Coefficient defining carbon mass of energy


'The carbon cycle
'****Initial values
'eq 10.35
series F
F = 2.3 ' Radiative forcing over pre-industrial levels (W/m^2)  
F.label(d) Radiative forcing over pre-industrial levels (W/m^2)
series F2
F2 = 3.8 ' Increase in radiative forcing due to doubling of CO2 concentration since pre-industrial levels (W/m^2)
F2.label(d) Increase in radiative forcing due to doubling of CO2 concentration \n since pre-industrial levels (W/m^2)
series CO2_atm_pre
CO2_atm_pre = 2156.2 'Pre-industrial CO2 concentration in atmosphere (Gt) 
CO2_atm_pre.label(d) Pre-industrial CO2 concentration in atmosphere (Gt)
'eq 10.36
series F_ex
F_ex = 0.28 ' Radiative forcing over pre-industrial levels (W/m^2) due to non-CO2 greenhouse gases (W/m^2) 
F_ex.label(d) Radiative forcing over pre-industrial levels (W/m^2) \n due to non-CO2 greenhouse gases (W/m^2)
series fex
fex = 0.005 ' Annual increase in radiative forcing due to non-CO2 greenhouse gas emissions (W/m^2) 
fex.label(d) Annual increase in radiative forcing due to non-CO2 greenhouse \n gas emissions (W/m^2)
'eq 10.37
series Temp_atm
Temp_atm = 0.91 'Atmospheric temperature over pre-industrial levels 
Temp_atm.label(d) Atmospheric temperature
series Temp_atm_ob
Temp_atm_ob=0.91 'Observed 2017 NASA temperature anomaly 
Temp_atm_ob.label(d) Observed 2017 NASA temperature anomaly 
'eq 10.38
series Temp_ocn
Temp_ocn = 0 'Lower ocean temperature over pre-industrial levels  
Temp_ocn.label(d) Temperature of the lower ocean
'eq 10.39
series CO2_atm 
CO2_atm = CO2_atm_pre 'Initial level of atmospheric CO2 concentration in 1960
CO2_atm.label(d) Atmospheric CO2 concentration
'eq 10.40
series CO2_br_pre
CO2_br_pre = 4950.5 ' Pre-industrial CO2 concentration in upper ocean/biosphere (Gt) 
CO2_br_pre.label(d) Pre-industrial CO2 concentration in upper ocean/biosphere (Gt) 
series CO2_br 
CO2_br = CO2_br_pre 'Upper ocean/biosphere CO2 concentration  
CO2_br.label(d) Upper ocean/biosphere CO2 concentration 
'eq 10.41
series CO2_ocn_pre
CO2_ocn_pre = 36670 ' Pre-industrial CO2 concentration in lower ocean (Gt)
CO2_ocn_pre.label(d) Pre-industrial CO2 concentration in lower ocean (Gt)
series CO2_ocn
CO2_ocn = CO2_ocn_pre  'Lower ocean CO2 concentration
CO2_ocn.label(d) Lower ocean CO2 concentration

'****Fixed Parameters
'eq 10.37
series t1
t1 = 0.027*0.026 'Speed of adjustment parameter in atmospheric temperature function ' 
t1.label(d) Speed of adjustment parameter in atmospheric temperature function
series t2
t2 = 0.018 'Coefficient of heat loss from the atmosphere to the lower ocean in atmospheric temperature function  
t2.label(d) Coefficient of heat loss from the atmosphere to the lower ocean in \n atmospheric temperature function 
series sens
sens = 3  'Equilibrium climate sensitivity  
sens.label(d) Equilibrium climate sensitivity
'eq 10.38
series t3
t3.label(d) Coefficient of heat loss from the atmosphere to the lower ocean in \n lower ocean temperature function
t3 = 0.005 'Coefficient of heat loss from the atmosphere to the lower ocean in lower ocean temperature function

'****Fixed Parameters
'eq 10.39
series phi11
phi11 = 0.9817 'CO2 transfer coefficient 
phi11.label(d) CO2 transfer coefficient
series phi21 
phi21 = 0.0080 'CO2 transfer coefficient
phi21.label(d) CO2 transfer coefficient
'eq 10.40
series phi12
phi12 = 0.0183 'CO2 transfer coefficient
phi12.label(d) CO2 transfer coefficient
series phi22
phi22 = 0.9915 'CO2 transfer coefficient
phi22.label(d) CO2 transfer coefficient
series phi32 
phi32 = 0.0001 'CO2 transfer coefficient
phi32.label(d) CO2 transfer coefficient
'eq 10.41
series phi23
phi23 = 0.0005 'CO2 transfer coefficient
phi23.label(d) CO2 transfer coefficient
series phi33 
phi33 = 0.9999 'CO2 transfer coefficient
phi33.label(d) CO2 transfer coefficient



'Note: maximum temperature rise depends also on non_CO2 radiative forcing due to methane, nitrous oxide, aerosols and other anthropogenic factors (see IPCC 2018, p. 7)


'Ecological efficiency
'****Variable Parameters
'eq 10.50 and 10.53
series beta_g
beta_g = 0.048154 - 0.01 'CO2 intensity of green capital (Gt/Ej)
beta_g.label(d)  CO2 intensity coefficient of green production
series beta_b
beta_b = 0.048154 + 0.01 'CO2 intensity of conventional capital (Gt/Ej)
beta_b.label(d)  CO2 intensity coefficient of conventional production
series beta_nre
beta_nre.label(d) Industrial emissions of CO2
series g_beta
g_beta =0
g_beta.label(d) Rate of decline of CO2 intensity 
'eq 10.51 and 10.54
series epsilon_g
epsilon_g = 7.65 'Energy intensity of green capital  (Ej/USD)
epsilon_g.label(d) Energy intensity coefficient of green production 
series epsilon_b 
epsilon_b = 9.32 'Energy intensity of conventional capital (Ej/USD)
epsilon_b.label(d) Energy intensity coefficient of conventional production
series epsilon_en
epsilon_en.label(d) 'Energy intensity coefficient in Brownland
series epsilon_en
epsilon_en = @recode(@date<@dateval("2020"),epsilon_b,(epsilon_g*(K_g/K) + epsilon_b*(K_b/K) )) 'Energy intensity coefficient  
'eq 10.52 and 10.55
series eta_g
eta_g = 0.075 'Share of renewable energy to total energy in Brownland, green capital
eta_g.label(d) Share of renewable energy to total energy, green capital
series eta_b
'---eta_b = 0 'Share of renewable energy to total energy in Brownland, conventional capital 
eta_b = 1-0.075 'Share of renewable energy to total energy in Brownland, conventional capital 
eta_b.label(d) Share of renewable energy to total energy, conventional capital
series eta_re
eta_re=0
eta_re.label(d) Share of renewable energy to total energy, average T


'Ecosystemic retroaction
'****Initial values
'eq 10.56
series dep_mat
dep_mat.label(d) Matter depletion ratio 
'eq 10.57
series dep_en
dep_en.label(d) Energy depletion ratio 
'eq 10.58
series dmg_ecs
dmg_ecs = 0.0028 'Percentage of damages (initial value) 
dmg_ecs.label(d) Proportional gross damage (0 = no damage; 1 = catastrophe)

'****Fixed Parameters
'eq 10.58
series dmg1
dmg1 = 0 'Parameter of damage function   
dmg1.label(d) Parameter in damage function
series dmg2
dmg2.label(d) Parameter in damage function
dmg2 = 0.00284/3 'Parameter of damage function
series dmg3
dmg3.label(d) Parameter in damage function
dmg3 = 0.000005/3 'Parameter of damage function 
series dmg4
dmg4 = 6.6754/3 'Parameter of damage function 
dmg4.label(d) Parameter in damage function






